name: Generate 3D Contribution Calendar

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily to keep the graph updated
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate 3D Contribution Calendar
        uses: yoshi389111/github-3d-contribution-calendar@v1
        with:
          # Update the GitHub username
          username: MihirParmar011
          output-dir: ./3d-calendar
          config: |
            {
              "contribution-stats": true,
              "streak-stats": true,
              "theme": "classic", # Other options: modern, futuristic
              "language": "en"
            }

      - name: Push Calendar to Repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update 3D Contribution Calendar"
          git push
